routes:
  rotundan:
    pc2ls_min_height: -0.05
    pc2ls_max_height: 0.10
  road_to_west:
    pc2ls_min_height: -0.39
    pc2ls_max_height: 0.4
  parkinglot_west:
    pc2ls_min_height: -0.385
    pc2ls_max_height: 0.20
  road_to_spawn:
    pc2ls_min_height: -0.40
    pc2ls_max_height: 0.40
  road_to_east:
    pc2ls_min_height: -0.19
    pc2ls_max_height: 0.50
  road_to_strip:
    pc2ls_min_height: -0.40
    pc2ls_max_height: 0.40
  strip:
    pc2ls_min_height: -0.36
    pc2ls_max_height: 0.12

# Optional per-waypoint runtime overrides. The UGV Nav2 driver applies these
# before sending the matching waypoint goal.
waypoints:

  road_to_west_3:
    pc2ls_min_height: -0.05
    pc2ls_max_height: 0.4
  road_to_west_4:
    pc2ls_min_height: -0.36
    pc2ls_max_height: 0.10
  road_to_west_5:
    pc2ls_min_height: -0.36
    pc2ls_max_height: 0.10
  road_to_west_6:
    pc2ls_min_height: -0.29
    pc2ls_max_height: 0.50
  road_to_west_8:
    pc2ls_min_height: -0.09
    pc2ls_max_height: 0.40

  road_to_spawn_3:
    pc2ls_min_height: -0.325
    pc2ls_max_height: 0.05
  road_to_spawn_4:
    pc2ls_min_height: -0.31
    pc2ls_max_height: 0.4
  road_to_spawn_5:
    pc2ls_min_height: -0.18
    pc2ls_max_height: 0.5
  road_to_spawn_7:
    pc2ls_min_height: -0.05
    pc2ls_max_height: 0.5
  road_to_spawn_9:
    pc2ls_min_height: -0.37
    pc2ls_max_height: 0.5

  road_to_east_1:
    pc2ls_min_height: -0.37
    pc2ls_max_height: 0.4
  road_to_east_3:
    pc2ls_min_height: -0.26
    pc2ls_max_height: 0.4
  road_to_east_6:
    pc2ls_min_height: -0.36
    pc2ls_max_height: 0.4

